# Generated by Django 5.0.6 on 2026-05-15 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Cliente')),
                ('people_count', models.PositiveIntegerField(default=1, verbose_name='Número de Pessoas')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADO', 'Chamado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
                'ordering': ['created_at'],
            },
        ),
    ]
