# Generated by Django 5.0.6 on 2026-08-27 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tickets', to='tables.table', verbose_name='Mesa destinada'),
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADO', 'Chamado'), ('SENTADO', 'Na mesa'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=15, verbose_name='Status'),
        ),
    ]
