# Generated by Django 5.0.6 on 2026-09-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_queueticket_table_alter_queueticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='priority_category',
            field=models.CharField(choices=[('NENHUMA', 'Sem prioridade'), ('IDOSO_80', 'Idoso(a) — 80 anos ou mais'), ('PCD', 'Pessoa com deficiência'), ('IDOSO_60', 'Idoso(a) — 60 a 79 anos'), ('GESTANTE', 'Gestante'), ('LACTANTE', 'Lactante'), ('COLO', 'Pessoa com criança de colo'), ('OBESIDADE', 'Pessoa com obesidade')], default='NENHUMA', max_length=10, verbose_name='Prioridade'),
        ),
    ]
