# Generated by Django 5.0.6 on 2026-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0003_queueticket_priority_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Código'),
        ),
    ]
