# Generated by Django 5.0.6 on 2026-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada'), ('CONTA', 'Aguardando pagamento'), ('RESERVADA', 'Reservada'), ('LIMPEZA', 'Em Limpeza')], default='LIVRE', max_length=15, verbose_name='Status'),
        ),
    ]
