/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/caixa` | `/caixa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cozinha` | `/cozinha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fila` | `/fila`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedidos` | `/pedidos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedidos/[id]` | `/pedidos/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/caixa` | `/caixa`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cozinha` | `/cozinha`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/fila` | `/fila`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mesas` | `/mesas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pedidos` | `/pedidos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pedidos/[id]` | `/pedidos/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/caixa${`?${string}` | `#${string}` | ''}` | `/caixa${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cozinha${`?${string}` | `#${string}` | ''}` | `/cozinha${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/fila${`?${string}` | `#${string}` | ''}` | `/fila${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mesas${`?${string}` | `#${string}` | ''}` | `/mesas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pedidos${`?${string}` | `#${string}` | ''}` | `/pedidos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/caixa` | `/caixa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cozinha` | `/cozinha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fila` | `/fila`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pedidos` | `/pedidos`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/pedidos/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/pedidos/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/pedidos/[id]` | `/pedidos/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
