# Generated by Django 5.0.6 on 2026-08-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fiscal_cest',
            field=models.CharField(blank=True, max_length=7, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fiscal_cfop',
            field=models.CharField(blank=True, max_length=4, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fiscal_csosn',
            field=models.CharField(blank=True, max_length=3, verbose_name='CSOSN'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fiscal_ncm',
            field=models.CharField(blank=True, max_length=8, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fiscal_origem',
            field=models.CharField(blank=True, max_length=1, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fiscal_unit',
            field=models.CharField(blank=True, max_length=3, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem', verbose_name='Item do cardápio'),
        ),
    ]
