# Generated by Django 5.0.6 on 2026-08-27 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_fiscal_cest_orderitem_fiscal_cfop_and_more'),
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='queue_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='queue.queueticket', verbose_name='Senha de origem'),
        ),
    ]
