# Generated by Django 5.0.6 on 2026-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto'), ('FECHAMENTO', 'Conta fechada (aguardando caixa)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15, verbose_name='Status'),
        ),
    ]
