# Generated by Django 5.0.6 on 2026-09-08 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_items', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retirado em'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_items', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
    ]
