# Generated by Django 5.0.6 on 2026-08-27 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_fiscal_cest_orderitem_fiscal_cfop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual')),
                ('regime_tributario', models.CharField(default='1', help_text='1 = Simples Nacional', max_length=1, verbose_name='Regime (CRT)')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('municipio_ibge', models.CharField(blank=True, max_length=7, verbose_name='Código IBGE do município')),
                ('municipio_nome', models.CharField(blank=True, max_length=120, verbose_name='Município')),
                ('logradouro', models.CharField(blank=True, max_length=160, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('fone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('environment', models.CharField(choices=[('2', 'Homologação'), ('1', 'Produção')], default='2', max_length=1, verbose_name='Ambiente')),
                ('serie_nfce', models.PositiveIntegerField(default=1, verbose_name='Série da NFC-e')),
                ('proximo_numero', models.PositiveIntegerField(default=1, verbose_name='Próximo número')),
                ('csc_id', models.CharField(blank=True, max_length=6, verbose_name='ID do CSC (idToken)')),
                ('csc_token', models.CharField(blank=True, max_length=64, verbose_name='CSC (token)')),
                ('certificado_path', models.CharField(blank=True, max_length=255, verbose_name='Caminho do certificado A1')),
                ('certificado_senha', models.CharField(blank=True, max_length=128, verbose_name='Senha do certificado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Fiscal',
                'verbose_name_plural': 'Configuração Fiscal',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('serie', models.PositiveIntegerField(blank=True, null=True, verbose_name='Série')),
                ('codigo_numerico', models.CharField(blank=True, max_length=8, verbose_name='Código numérico (cNF)')),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44, verbose_name='Chave de acesso')),
                ('ambiente', models.CharField(choices=[('2', 'Homologação'), ('1', 'Produção')], default='2', max_length=1, verbose_name='Ambiente')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ASSINADA', 'Assinada'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('NAO_CONFIGURADO', 'Não configurado')], default='RASCUNHO', max_length=16, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor total')),
                ('xml', models.TextField(blank=True, verbose_name='XML')),
                ('xml_assinado', models.TextField(blank=True, verbose_name='XML assinado')),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=20, verbose_name='Protocolo')),
                ('qr_code_data', models.TextField(blank=True, verbose_name='QR Code (URL)')),
                ('url_consulta', models.URLField(blank=True, verbose_name='URL de consulta')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Mensagem SEFAZ / motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorizada_em', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'NFC-e',
                'verbose_name_plural': 'NFC-e',
                'ordering': ['-created_at'],
            },
        ),
    ]
