# Generated by Django 5.0.6 on 2026-08-27 20:38

import apps.menu.fiscal
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria do Cardápio',
                'verbose_name_plural': 'Categorias do Cardápio',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('sector', models.CharField(choices=[('COZINHA', 'Cozinha'), ('PARRILLA', 'Parrilla'), ('BAR', 'Bar')], default='COZINHA', max_length=10, verbose_name='Setor de preparo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de venda')),
                ('preparation_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de preparo (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='Código interno (SKU)')),
                ('barcode_gtin', models.CharField(blank=True, help_text='Deixe em branco para "SEM GTIN".', max_length=14, validators=[apps.menu.fiscal.validate_gtin], verbose_name='GTIN/EAN')),
                ('unit_commercial', models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('DZ', 'Dúzia'), ('PT', 'Porção'), ('CX', 'Caixa'), ('GF', 'Garrafa')], default='UN', max_length=3, verbose_name='Unidade comercial')),
                ('unit_taxable', models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('DZ', 'Dúzia'), ('PT', 'Porção'), ('CX', 'Caixa'), ('GF', 'Garrafa')], default='UN', max_length=3, verbose_name='Unidade tributável')),
                ('origem', models.CharField(choices=[('0', '0 - Nacional (exceto 3, 4, 5 e 8)'), ('1', '1 - Estrangeira - importação direta (exceto 6)'), ('2', '2 - Estrangeira - adquirida no mercado interno (exceto 7)'), ('3', '3 - Nacional, conteúdo de importação > 40% e <= 70%'), ('4', '4 - Nacional, produção conforme processos produtivos básicos'), ('5', '5 - Nacional, conteúdo de importação <= 40%'), ('6', '6 - Estrangeira - importação direta, sem similar nacional (lista CAMEX)'), ('7', '7 - Estrangeira - mercado interno, sem similar nacional (lista CAMEX)'), ('8', '8 - Nacional, conteúdo de importação > 70%')], default='0', max_length=1, verbose_name='Origem da mercadoria')),
                ('ncm', models.CharField(max_length=8, validators=[apps.menu.fiscal.validate_ncm], verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=7, validators=[apps.menu.fiscal.validate_cest], verbose_name='CEST')),
                ('cfop', models.CharField(choices=[('5101', '5101 - Venda de produção do estabelecimento'), ('5102', '5102 - Venda de mercadoria adquirida de terceiros'), ('5103', '5103 - Venda de produção do estabelecimento (não contribuinte)'), ('5104', '5104 - Venda de mercadoria de terceiros (não contribuinte)'), ('5405', '5405 - Venda de mercadoria com ICMS-ST, na condição de substituído'), ('5656', '5656 - Venda de combustível/lubrificante adquirido de terceiros'), ('5933', '5933 - Prestação de serviço tributado pelo ISSQN')], default='5102', max_length=4, validators=[apps.menu.fiscal.validate_cfop], verbose_name='CFOP')),
                ('csosn', models.CharField(choices=[('101', '101 - Tributada pelo Simples Nacional com permissão de crédito'), ('102', '102 - Tributada pelo Simples Nacional sem permissão de crédito'), ('103', '103 - Isenção do ICMS no Simples Nacional para faixa de receita bruta'), ('201', '201 - Simples Nacional com permissão de crédito e cobrança de ICMS-ST'), ('202', '202 - Simples Nacional sem permissão de crédito e com cobrança de ICMS-ST'), ('203', '203 - Isenção do ICMS no Simples Nacional e com cobrança de ICMS-ST'), ('300', '300 - Imune'), ('400', '400 - Não tributada pelo Simples Nacional'), ('500', '500 - ICMS cobrado anteriormente por ST ou por antecipação'), ('900', '900 - Outros')], default='102', max_length=3, verbose_name='CSOSN')),
                ('icms_aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alíquota ICMS próprio (%)')),
                ('pis_cst', models.CharField(choices=[('01', '01 - Operação tributável com alíquota básica'), ('02', '02 - Operação tributável com alíquota diferenciada'), ('04', '04 - Operação tributável monofásica - revenda a alíquota zero'), ('06', '06 - Operação tributável a alíquota zero'), ('07', '07 - Operação isenta da contribuição'), ('08', '08 - Operação sem incidência da contribuição'), ('09', '09 - Operação com suspensão da contribuição'), ('49', '49 - Outras operações de saída')], default='49', max_length=2, verbose_name='CST PIS')),
                ('pis_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alíquota PIS (%)')),
                ('cofins_cst', models.CharField(choices=[('01', '01 - Operação tributável com alíquota básica'), ('02', '02 - Operação tributável com alíquota diferenciada'), ('04', '04 - Operação tributável monofásica - revenda a alíquota zero'), ('06', '06 - Operação tributável a alíquota zero'), ('07', '07 - Operação isenta da contribuição'), ('08', '08 - Operação sem incidência da contribuição'), ('09', '09 - Operação com suspensão da contribuição'), ('49', '49 - Outras operações de saída')], default='49', max_length=2, verbose_name='CST COFINS')),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alíquota COFINS (%)')),
                ('fisco_info', models.CharField(blank=True, max_length=255, verbose_name='Informação adicional ao fisco')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.menucategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'ordering': ['category__display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sector'], name='menu_menuit_is_acti_167bfb_idx'), models.Index(fields=['ncm'], name='menu_menuit_ncm_d76ec8_idx')],
            },
        ),
    ]
