# Generated by Django 5.0.6 on 2026-09-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_orderitem_created_by_orderitem_removed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('sector', models.CharField(choices=[('COZINHA', 'Cozinha'), ('PARRILLA', 'Parrilla'), ('BAR', 'Bar / Bebidas'), ('CAIXA', 'Caixa / Recibo')], max_length=10, verbose_name='Setor')),
                ('qz_printer_name', models.CharField(help_text='Exatamente como o nome aparece no sistema operacional / QZ Tray.', max_length=200, verbose_name='Impressora no QZ Tray')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('copies', models.PositiveSmallIntegerField(default=1, verbose_name='Vias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Toca do Espanhol', max_length=120, verbose_name='Título do cabeçalho')),
                ('header_image', models.TextField(blank=True, verbose_name='Logo / imagem (data URL base64)')),
                ('watermark_text', models.CharField(blank=True, max_length=80, verbose_name="Marca d'água")),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='Rodapé')),
                ('font_family', models.CharField(choices=[('A', 'Padrão (A)'), ('B', 'Condensada (B)')], default='A', max_length=1, verbose_name='Fonte')),
                ('font_size', models.PositiveSmallIntegerField(default=1, verbose_name='Tamanho (1 a 4)')),
                ('bold', models.BooleanField(default=True, verbose_name='Negrito')),
                ('align', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=6, verbose_name='Alinhamento')),
                ('margin_left', models.PositiveSmallIntegerField(default=0, verbose_name='Margem esquerda (colunas)')),
                ('margin_top', models.PositiveSmallIntegerField(default=0, verbose_name='Linhas em branco no topo')),
                ('margin_bottom', models.PositiveSmallIntegerField(default=3, verbose_name='Linhas em branco no fim')),
                ('paper_width', models.PositiveSmallIntegerField(default=48, verbose_name='Largura do papel (colunas)')),
                ('cut_paper', models.BooleanField(default=True, verbose_name='Cortar papel ao final')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de impressão',
                'verbose_name_plural': 'Configuração de impressão',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=10, verbose_name='Setor')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Conteúdo (texto puro)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Na fila'), ('IMPRESSO', 'Impresso'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='orders.orderitem')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='printing.printer')),
            ],
            options={
                'verbose_name': 'Trabalho de impressão',
                'verbose_name_plural': 'Fila de impressão',
                'ordering': ['id'],
            },
        ),
    ]
